version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  stress-test:
    lang: python3-http
    handler: ./stress-test
    image: jfan981/stress-test:v5-final
    labels:
      com.openfaas.scale.min: 5
      com.openfaas.scale.max: 5

