version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  stress-test:
    lang: python3-http
    handler: ./stress-test
    image: jfan981/stress-test:v5-final
    
    # Prevents OpenFaaS from timing out during heavy stress tests
    environment:
      read_timeout: 60s
      write_timeout: 60s
      exec_timeout: 60s

    labels:
      # Lock replicas to the number of physical CPU cores (2 vCPUs)
      com.openfaas.scale.min: 2
      com.openfaas.scale.max: 2